### ISSUE TITLE
M2: Create and manage Branches

### ISSUE THREAD

**Issue by apexhydra** [Team-73-Git-Gud/CS-2340-Software#7]
Add and remove files
Each team member should add a text file on the master branch to the top level directory labeled
readme.pn.txt where the pn would be p1, p2, p3, p4 or p5 based upon which person you are for the lab.
The contents of the file can really be anything, but should include your name and email. Each team 
member should delete the text file useless.pn.txt where pn is p1,p2, p3, p4 or p5 based on your team
member number. Do NOT delete the wrong files!!
Use good descriptive Log comments for your changes/commits
Roll back changes by viewing (checkout) your original branch from an earlier step. Verify that none of
the changes you have made are in the original branch project version you checked out.

**Comment by CollinAvidano** [comment]
PLEASE DO NOT COMMIT TO THIS REPO FOR M2
